development:
  adapter: mysql2
  encoding: utf8
  database: kandage 
  host: localhost
  username: root
  password: ian770624

test:
  adapter: mysql2
  encoding: utf8
  database: kandage_test
  host: localhost
  username: root
  password: ian770624

production:
  adapter: mysql2
  encoding: utf8
  database: kandage
  host: localhost
  username: root
  password: ian770624

