# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140221154239) do

  create_table "companies", force: true do |t|
    t.integer "symbol"
    t.string  "name",   limit: 64, null: false
  end

  create_table "m_data", force: true do |t|
    t.integer "company_id"
    t.integer "month"
    t.integer "is_consolidated"
    t.float   "month_average_price"
    t.float   "month_revenue"
    t.float   "month_revenue_per_share"
    t.float   "cash_dividend_yield"
    t.float   "cash_dividend_yield_three_year"
    t.float   "cash_dividend_yield_five_year"
    t.float   "cash_dividend_yield_three_year_sixteen_multiples"
    t.float   "cash_dividend_yield_three_year_twenty_multiples"
    t.float   "cash_dividend_yield_three_year_thirty_two_multiples"
    t.float   "cash_dividend_yield_five_year_sixteen_multiples"
    t.float   "cash_dividend_yield_five_year_twenty_multiples"
    t.float   "cash_dividend_yield_five_year_thirty_two_multiples"
  end

  create_table "q_data", force: true do |t|
    t.integer "company_id"
    t.integer "quarter"
    t.integer "is_consolidated"
    t.float   "revenue"
    t.float   "gross_profit"
    t.float   "operating_profit"
    t.float   "net_profit"
    t.float   "eps"
    t.float   "eps_four_quarter"
    t.float   "average_eps_four_quarter"
    t.float   "current_assets"
    t.float   "long_term_investments"
    t.float   "fixed_assets"
    t.float   "total_assets"
    t.float   "current_liabilities"
    t.float   "long_term_liabilities"
    t.float   "total_liabilities"
    t.float   "net_asset_value"
    t.float   "share_capital"
    t.float   "book_value_per_share"
    t.float   "cash_flow_from_operating_activities"
    t.float   "cash_flow_from_investing_activities"
    t.float   "cash_flow_from_financing_activities"
    t.float   "free_cash_flow"
    t.float   "net_cash_flow"
    t.float   "debt_cash_flow"
    t.float   "ratio_of_liabilities_to_assets"
    t.float   "quick_ratio"
    t.float   "current_ratio"
    t.float   "interest_protection_multiples"
    t.float   "ratio_of_cash_from_operating_activities_to_current_liabilities"
    t.float   "ratio_of_cash_from_operating_activities_to_liabilities"
    t.float   "ratio_of_cash_from_operating_activities_to_net_profit"
    t.float   "account_receivable_turnover"
    t.float   "inventory_turnover"
    t.float   "fixed_property_and_equipment"
    t.float   "total_assets_turnover"
    t.float   "gross_profit_margin"
    t.float   "operating_profit_margin"
    t.float   "net_profit_margin"
    t.float   "roa"
    t.float   "roe"
    t.float   "roa_four_quarter"
    t.float   "roe_four_quarter"
    t.float   "reinvestment_rate"
    t.float   "cash_and_cash_equivalent"
    t.float   "temporary_investment"
    t.float   "account_and_notes_receivable"
    t.float   "inventory"
    t.float   "short_term_borrowing"
    t.float   "short_term_notes_payable"
    t.float   "accounts_and_notes_payable"
    t.float   "accounts_recevied_in_advanve"
    t.float   "long_term_liabilities_due_within_one_year"
    t.float   "prepayments"
    t.float   "short_term_financing_borrowing"
    t.float   "long_and_short_term_financing_borrowing"
    t.float   "ratio_of_short_term_borrowing_to_current_liabilities"
    t.float   "ratio_of_long_and_short_term_borrowing_to_current_liabilities"
    t.float   "ratio_of_cash_flow_from_operaing_activitie_to_revenue"
    t.float   "ratio_of_accounts_receivable_and_inventory_to_total_assets"
    t.float   "accounts_receivable_balance"
    t.float   "inventory_balance"
    t.float   "ratio_of_cash_and_short_term_investment_to_total_assets"
    t.float   "operating_cash_inflow_per_share"
    t.float   "investing_cash_outflow_per_share"
    t.float   "financing_cash_inflow_per_share"
    t.float   "free_cash_inflow_per_share"
    t.float   "net_cash_inflow_per_share"
    t.float   "days_payable_outstanding"
    t.float   "pretax_income"
    t.float   "pretax_income_ratio"
  end

  create_table "y_data", force: true do |t|
    t.integer "company_id"
    t.integer "year"
    t.integer "is_consolidated"
    t.float   "revenue"
    t.float   "gross_profit"
    t.float   "operating_profit"
    t.float   "net_profit"
    t.float   "eps"
    t.float   "current_assets"
    t.float   "long_term_investments"
    t.float   "fixed_assets"
    t.float   "total_assets"
    t.float   "current_liabilities"
    t.float   "long_term_liabilities"
    t.float   "total_liabilities"
    t.float   "net_asset_value"
    t.float   "share_capital"
    t.float   "book_value_per_share"
    t.float   "cash_flow_from_operating_activities"
    t.float   "cash_flow_from_investing_activities"
    t.float   "cash_flow_from_financing_activities"
    t.float   "free_cash_flow"
    t.float   "net_cash_flow"
    t.float   "debt_cash_flow"
    t.float   "ratio_of_liabilities_to_assets"
    t.float   "quick_ratio"
    t.float   "current_ratio"
    t.float   "interest_protection_multiples"
    t.float   "ratio_of_cash_from_operating_activities_to_current_liabilities"
    t.float   "ratio_of_cash_from_operating_activities_to_liabilities"
    t.float   "ratio_of_cash_from_operating_activities_to_net_profit"
    t.float   "account_receivable_turnover"
    t.float   "inventory_turnover"
    t.float   "fixed_property_and_equipment"
    t.float   "total_assets_turnover"
    t.float   "gross_profit_margin"
    t.float   "operating_profit_margin"
    t.float   "net_profit_margin"
    t.float   "roa"
    t.float   "roe"
    t.float   "cash_and_cash_equivalent"
    t.float   "temporary_investment"
    t.float   "account_and_notes_receivable"
    t.float   "inventory"
    t.float   "short_term_borrowing"
    t.float   "short_term_notes_payable"
    t.float   "accounts_and_notes_payable"
    t.float   "accounts_recevied_in_advanve"
    t.float   "long_term_liabilities_due_within_one_year"
    t.float   "prepayments"
    t.float   "short_term_financing_borrowing"
    t.float   "long_and_short_term_financing_borrowing"
    t.float   "ratio_of_short_term_borrowing_to_current_liabilities"
    t.float   "ratio_of_long_and_short_term_borrowing_to_current_liabilities"
    t.float   "ratio_of_cash_flow_from_operaing_activitie_to_revenue"
    t.float   "ratio_of_accounts_receivable_and_inventory_to_total_assets"
    t.float   "accounts_receivable_balance"
    t.float   "inventory_balance"
    t.float   "ratio_of_cash_and_short_term_investment_to_total_assets"
    t.float   "operating_cash_inflow_per_share"
    t.float   "investing_cash_outflow_per_share"
    t.float   "financing_cash_inflow_per_share"
    t.float   "free_cash_inflow_per_share"
    t.float   "net_cash_inflow_per_share"
    t.float   "days_payable_outstanding"
    t.float   "pretax_income"
    t.float   "pretax_income_ratio"
    t.float   "ratio_of_dividend_to_free_cash"
    t.float   "average_ratio_of_dividend_to_free_cash_due_within_five_years"
  end

end
